### ISSUE TITLE
fd in Bar() is not closed

### ISSUE THREAD

**Issue by micpez** [heikoengel/pyPCIe#1]
When Bar() is deleted, mmap is closed but fd is left open:

    def __del__(self):
        if self.__map is not None:
            self.__map.close()

I happend to loop and create several times Bar() for the same pci sbdf and I got:
OSError: [Errno 24] Too many open files

Saving fd and closing it solved the issue:

    def __del__(self):
        if self.__map is not None:
            self.__map.close()
        os.close(self._fd)

**Comment by heikoengel** [comment]
Thanks!

**Comment by micpez** [comment]
You're welcome!
Any plans to push a new version to pypy appreciated.

**Comment by heikoengel** [comment]
should be available on pypi now as version 0.1.1
